apiVersion: v1
kind: Namespace
metadata: 
  name: psnr
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: replicacontroller
  labels: 
    app: controller
  namespace: psnr   
spec:
  replicas: 3
  selector:
    app: controller
  template:
    metadata:
      labels:
        app: controller  
    spec: 
      containers: 
        - name: database         
          image: mariadb
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: psnr
  labels:
    app: controller
spec: 
  type: ClusterIP
  selector: 
    app: controller
  ports:
    - port: 3306
      targetPort: 3306
