apiVersion: v1
kind: Namespace
metadata: 
  name: personalSpace
  labels: 
    app: personal
---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels:
    app: my-pod
  namespace: personalSpace 
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels: 
    app: my-pod 
  namespace: personalSpace    
spec: 
  type: ClusterIP
  selector:
    app: my-pod
  ports: 
    - port: 80
      targetPort: 80
