apiVersion: v1
kind: Namespace
metadata:
   name: ppn
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:              
    - ReadWriteOnce          
  storageClassName: default  
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:      
    volumeID: vol-097271e5751a9cd01
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: ppn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: default

---
apiVersion: v1  
kind: Pod
metadata:
   name: pvcpod
   labels:
      app: pvcpod
   namespace: ppn   
spec: 
   containers:  
       - name: pvcnginx
         image: nginx
         ports:
           - containerPort: 80
         volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: my-vol
   volumes:  
       - name: my-vol
         persistentVolumeClaim:  
             claimName: my-pvc 

---
apiVersion: v1 
kind: Service
metadata: 
    name: servicepvc
    namespace: ppn
spec: 
   type: ClusterIP
   selector:
      app: pvcpod
   ports: 
     - port: 80
       targetPort: 80       


           


     

